namespace Pixelakes.Wrath.Enums {
	public enum Target{
		None				= 0, //No Target
		Player				= 100, //Player level, like skip turn or reduce points
		Opponent				= 101, //Opponent level, like skip turn or reduce points
		AllPlayers				= 103, //Both Player and Opponet level
		RandomPlayer				= 104, //Chooses the player at random
		PlayerHand				= 105, //Cards in the player's hand
		OpponentHand				= 106, //Cards in the opponent's hand
		PlayerDeck				= 107, //Player's remaining Cards in Deck
		OpponentDeck				= 108, //Player's remaining Cards in Deck
		ThisCard				= 200, //The card using the ability
		PlayerCard				= 201, //Initiator chooses any player card in play
		OpponentCard				= 202, //Initiator chooses any Opponent card in play
		RandomPlayerCard				= 203, //System picks random player card in play
		RandomOpponentCard				= 204, //System picks random Opponent card in play
		RandomCard				= 205, //System picks random card in play
		AllPlayerCards				= 206, //All of the player cards in play
		AllOpponentCards				= 207, //All of the Opponent cards in play
		AllCards				= 208, //All cards in play
		CardOnLeft				= 209, //Card to left of card
		CardOnRight				= 210, //Card to Right of card
		Neighbors				= 211, //ards on both sides of card
		PlayerCommander				= 300, //Player's Commnader
		OpponentCommander				= 301, //Opponent's Commander
		PlayerWonder				= 302, //Player's Wonder Card
		OpponentWonder				= 303, //Opponent'sWonder Card
		Row				= 400, //All cards in same row as card
		PlayerRow				= 401, //Initiator chooses any row on the player's side
		OpponentRow				= 402, //Initiator chooses any row on the opponent's side
		OpposingRow				= 403, //Opponent's row matching card's row
		StrongestPlayer				= 500, //Strongest player unit card
		StrongestOpponent				= 501, //Strongest opponent unit card
		WeakestPlayer				= 502, //Weakest player unit card
		WeakestOpponent				= 503, //Weakest opponent unit card
		PlayerBoosted				= 600, //Player cards that are currently Boosted
		OpponentBoosted				= 601, //Opponent cards that are currently Boosted
		AllPlayerBoosted				= 602, //All Player cards that are currently Boosted
		AllOpponentBoosted				= 603, //All Opponent cards that are currently Boosted
		PlayerProtected				= 604, //Player cards that are currently Protected
		OpponentProtected				= 605, //Opponent cards that are currently Protected
		AllPlayerProtected				= 606, //All Player cards that are currently Protected
		AllOpponentProtected				= 607, //All Opponent cards that are currently Protected
		PlayerImmuned				= 608, //Player cards that are currently Immuned
		OpponentImmuned				= 609, //Opponent cards that are currently Immuned
		AllPlayerImmuned				= 610, //All Player cards that are currently Immuned
		AllOpponentImmuned				= 611, //All Opponent cards that are currently Immuned
		PlayerLocked				= 612, //Player cards that are currently Locked
		OpponentLocked				= 613, //Opponent cards that are currently Locked
		AllPlayerLocked				= 614, //All Player cards that are currently Locked
		AllOpponentLocked				= 615, //All Opponent cards that are currently Locked
		PlayerStealth				= 616, //Player cards that are currently in Stealth
		OpponentStealth				= 617, //Opponent cards that are currently in Stealth
		AllPlayerStealth				= 618, //All Player cards that are currently in Stealth
		AllOpponentStealth				= 619, //All Opponent cards cards that are currently in Stealth
   }
}